### PR TITLE
Fix port to rustdct 0.7

### PR DESCRIPTION
**Pull request by sdroege**
process_dct2_with_scratch() operates inplace now and the second parameter is the scratch space, not the output.

### CODE REVIEW

**Comment by karpfediem** [comment]
Thanks for taking a look :)
Sadly i tried this branch but it's still barking about too little scratch space in in `img_hash/src/dct.rs:60:17`.
`thread 'tokio-runtime-worker' panicked at 'Not enough scratch space was provided. Expected scratch len >= 40, got scratch len = 10', /home/carp/.cargo/registry/src/github.com-1ecc6299db9ec823/rustdct-0.7.1/src/common.rs:104:5`

**Comment by sdroege** [comment]
What exactly are you running to reproduce that? Would seem useful to also add this as part of the tests :)

**Comment by karpfediem** [comment]
> What exactly are you running to reproduce that? Would seem useful to also add this as part of the tests :)

Just configuring a HasherConfig with `.preproc_dct` and then trying to use hash_image should be enough.

This is the code it fails inside:
```rust
fn hash(image: Option<&DynamicImage>) -> Value {
    match image {
        Some(image) => {
            let hasher = image_hasher::HasherConfig::new()
                .hash_size(8, 8)
                .preproc_dct()
                .hash_alg(HashAlg::DoubleGradient)
                .to_hasher();
            Value::from(hasher.hash_image(image).to_base64())
        }
        _ => Value::None,
    }
}
```

You mention tests; where can i find/run tests for this library? :sweat_smile:

**Comment by sdroege** [comment]
There are some unit tests (and even more that are commented out). You can run those with `cargo test`. Apparently none of these covers the code in question.

**Comment by CrendKing** [comment]
Same problem as karp mentioned here. According to the stack trace, the panic happens at the first `row_dct.process_dct2_with_scratch`. This PR doesn't change that part (only a name change).

**Comment by sdroege** [comment]
Funny enough the tests are passing because they don't go through the DCT code. I'll extend them.

**Comment by sdroege** [comment]
This should be good now

**Comment by ssokolow** [comment]
@qarmin Sorry to say something so completely off-topic but, with issues turned off and no apparent contact options enabled on your profile...

I find `image::imageops::sample::resize` taking up 45% of my flamegraph using this. The fact that you've disabled issues suggests, to me, that you may be trying to funnel feature patches back to the upstream project... but I actually want something where there's an apparent chance of getting my contributions released on crates.io.

If I make time to add support for faster implementations like [resize](https://lib.rs/crates/resize) or [fast_image_resize](https://lib.rs/crates/fast_image_resize), would you prefer I open a PR here or publish a fork of your fork?

**Comment by qarmin** [comment]
@karpfediem @CrendKing can you confirm that problem is fixed?

@ssokolow issues are by default disabled in forks, so I enabled it and created issue about it #4

**Comment by CrendKing** [comment]
The problem is fixed for me.

**Comment by qarmin** [comment]
Thanks!

**Comment by karpfediem** [comment]
Fixed for me as well. Thanks!

**Pull request merged**
